name: Node Bump Version
description: Action to bump the version of a Nodejs project
inputs:
  pat:
    description: PAT for accessing the application repo
    required: true
  new-version:
    description: The new version to bump to
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.pat }}

    - name: Bump VERSION file
      run: |
        echo ${{ inputs.new-version }} > VERSION
      shell: bash

    - name: Bump package.json and package-lock.json
      run: |
        yq -i -j -P '.version = "${{ inputs.new-version }}"' 'package.json'
        yq -i -j -P '.version = "${{ inputs.new-version }}" | .packages[""].version = "${{ inputs.new-version }}"' 'package-lock.json'
      shell: bash

    - name: Bump image tags in helm values
      run: |
        yq -i '.image.tag = "${{ inputs.new-version }}"' './charts/values.dev.yaml'
        yq -i '.image.tag = "${{ inputs.new-version }}"' './charts/values.prod.yaml'
        if [ -f "./charts/values.stage.yaml" ]; then
          yq -i '.image.tag = "${{ inputs.new-version }}"' './charts/values.stage.yaml'
        fi
      shell: bash
    
    - name: Commit Changes
      env:
        GIT_AUTHOR_NAME: Beez Innovation Labs
        GIT_COMMITTER_NAME: Beez Innovation Labs
        GIT_AUTHOR_EMAIL: github@beezlabs.com
        GIT_COMMITTER_EMAIL: github@beezlabs.com
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "feat: bump version to ${{ inputs.new-version }}"
        git push
      shell: bash
